paragbaxi/qualysapi

qualysapi/api_actions.py, qualysapi/api_objects.py, qualysapi/connector.py
Added useful functions for some common tasks with the API and created object classes for Host, AssetGroup, and Scan. The QGConnector class now inherits from the QGActions class for convenience in using the additional functions (and splitting them off into a different file).
=> Added useful functions and object classes

qualysapi/api_actions.py, qualysapi/api_objects.py
Added Report and ReportTemplate objects and functions to view lists of them. Also fixed the listAssetGroups function.
=> Added Report and ReportTemplate objects, fixed listAssetGroups function 

qualysapi/api_actions.py
This allows for returning only the specific report object needed.
=> Added the capability to pass a report id to listReports()

.travis.yml, qualysapi/api_objects.py, qualysapi/contrib.py
Reduce __undefined names__ from 23 to 6.
* Comment out __requirements.txt__ line in __.travis.yml__
* Add __self__ to a couple of methods
* Add missing imports
* Remove an unused import
* Run __isort__ on imports
* Comment out an unused constant
=> Fix several issues discovered via flake8

qualysapi/config.py
Noticed these two lines stealing/duplicating my logging ;)
=> Root logger stealing

qualysapi/connector.py
See http://www.python-requests.org/en/latest/api/#requests.Response.text
=> Fix getting the response in text form

qualysapi/api_actions.py
Adding self in param list.
See #41
=> Missing instance param

.travis.yml, Makefile, README.md, reqs/dev-requirements.txt, reqs/requirements.txt
Add python `3.7` and `3.8-dev` to Travis CI
Allow for failure on branch `3.8-dev`
Add Travis CI build badge to readme
=> Add python 3.7 and 3.8-dev to CI

qualysapi/connector.py
Eg: /api/2.0/fo/asset/host/vm/detection/ with no
truncation limit
=> Add streaming request option for lengthy api calls

examples/qualysapi-virtualhost.py, qualysapi/api_actions.py, qualysapi/api_objects.py
Add support for basic function for virtual hosts, and a VirtualHost class
=> support basic virtual hosts functions

.travis.yml, README.md, qualysapi/__init__.py, qualysapi/api_actions.py, qualysapi/api_methods.py, qualysapi/api_objects.py, qualysapi/config.py, qualysapi/connector.py, qualysapi/settings.py, qualysapi/util.py, reqs/requirements.txt, setup.cfg, setup.py, tests/test_smoke.py
=> fix: supported versions of python

qualysapi/version.py, reqs/dev-requirements.txt, setup.py
=> fix future_fstrings breaking installation

pyproject.toml, setup.cfg, setup.py
* simplify `setup.py`
* add `pyproject.toml` ([PEP 518](https://www.python.org/dev/peps/pep-0518/))
=> Cleanup and simplify build system

.travis.yml, pyproject.toml, qualysapi/__init__.py, qualysapi/api_actions.py, qualysapi/api_methods.py, qualysapi/api_objects.py, qualysapi/config.py, qualysapi/connector.py, qualysapi/settings.py, qualysapi/util.py, qualysapi/version.py, tests/context.py, tests/test_smoke.py, tox.ini
=> Consistent styling w/ black and isort

.travis.yml
=> drop py3.5

tox.ini
=> test: simplify default tests and remove py35

qualysapi/api_actions.py, qualysapi/api_methods.py, qualysapi/api_objects.py, qualysapi/config.py, qualysapi/connector.py, qualysapi/settings.py, qualysapi/util.py, setup.cfg, tests/context.py, tests/test_smoke.py
* remove py3.5 from build tools
* remove `future_fstrings`
closes: #74
=> feat: drop python 3.5

pyproject.toml, qualysapi/api_actions.py, qualysapi/api_methods.py, qualysapi/config.py, qualysapi/connector.py, setup.py, tox.ini
* use f-strings
* logging - lazy str interpolation
* removed py2-isms
* removed py35 from black config
=> chore: code cleanup

qualysapi/api_actions.py
There was an issue with the last commits from my PRs, and #81 overwrote #80 changes. Repushing the changes from #80 into this PR.
=> Fix not scanned since branch

qualysapi/api_actions.py
Adding two functions for launching and downloading reports.
On behalf of DB Systel GmbH
=> extend report api

qualysapi/api_actions.py, qualysapi/connector.py
api_actions - included method to listHosts and childtags, and included more error handling for listReports - similar to launchReports
On Behalf of DB Systel
=> Extend Functionaly and include more Error Handling

qualysapi/util.py
This reverts commit 3eb08c7b2c2fcd78ab93bd5fd976bcdb3fe37e20.
Fixes #103
=> Revert "fix special characters in password"
